name: 'rio_brt_data'
version: '1.0.0'
config-version: 2

profile: 'rio_brt_data'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"
  - "macros"
  - "analyses"
  - "seeds"
  - "snapshots"

models:
  rio_brt_data:
  +schema: public  
  materialized: table

  select_data_brt:
  +schema: public
  +materialized: view
